export const ActionTypes = {
    FETCH_EMPLOYEES_REQUEST: "FETCH_EMPLOYEES_REQUEST",
    FETCH_EMPLOYEES_SUCCESS: "FETCH_EMPLOYEES_SUCCESS",
    FETCH_EMPLOYEES_FAILURE: "FETCH_EMPLOYEES_FAILURE",
    FETCH_EMPLOYEE_BY_ID_REQUEST: "FETCH_EMPLOYEE_BY_ID_REQUEST",
    FETCH_EMPLOYEE_BY_ID_SUCCESS: "FETCH_EMPLOYEE_BY_ID_SUCCESS",
    FETCH_EMPLOYEE_BY_ID_FAILURE: "FETCH_EMPLOYEE_BY_ID_FAILURE",
    ADD_EMPLOYEE_REQUEST: "ADD_EMPLOYEE_REQUEST",
    ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
    ADD_EMPLOYEE_FAILURE: "ADD_EMPLOYEE_FAILURE",
    UPDATE_EMPLOYEE_REQUEST: "UPDATE_EMPLOYEE_REQUEST",
    UPDATE_EMPLOYEE_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
    UPDATE_EMPLOYEE_FAILURE: "UPDATE_EMPLOYEE_FAILURE",
    DELETE_EMPLOYEE_REQUEST: "DELETE_EMPLOYEE_REQUEST",
    DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
    DELETE_EMPLOYEE_FAILURE: "DELETE_EMPLOYEE_FAILURE",
  };
  